[package]
name = "fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loro = { path = "../loro", features = ["test_utils"] }
arbitrary = "1"
tabled = "0.10"
debug-log = { workspace = true }
fxhash = { workspace = true }
enum_dispatch = { workspace = true }
enum-as-inner = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arbtest = "^0.2.0"
ctor = "0.1.23"
color-backtrace = { version = "0.5" }
tracing-subscriber = "0.3.18"
tracing-chrome = "0.7.1"
