[package]
name = "loro-common"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Common types and functions for Loro. This is an internal lib of Loro."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.43"
rle = { path = "../rle", version = "0.1.0", package = "loro-rle" }
wasm-bindgen = { version = "=0.2.86", optional = true }
fxhash = "0.2.1"
enum-as-inner = "0.6.0"
string_cache = "0.8"
arbitrary = { version = "1.3.0", features = ["derive"] }
js-sys = { version = "0.3.60", optional = true }
serde_columnar = "0.3.3"

[features]
wasm = ["wasm-bindgen", "js-sys"]
